[workspace]
resolver = "2"
members = [
    "lib",
    "macros",
]

[workspace.package]
authors = [
    "Ash Manning <ash@layertwolabs.com>",
]
edition = "2021"
license-file = "LICENSE.txt"
publish = false
version = "0.1.0"
